name: brain_fusion
description: Fusion Brain AI is a new AI art generation tool that can create amazing images form just text prompt.
homepage: https://github.com/8BitCoderz/brain_fusion/
repository: https://github.com/8BitCoderz/brain_fusion/
issue_tracker: https://github.com/8BitCoderz/brain_fusion/issues
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  http: ^0.13.6

dev_dependencies:
  test: ^1.24.2

