name: brain_fusion
description: Fusion Brain AI is a new AI art generation tool that can create amazing images form just text prompt.
version: 0.0.6
homepage: https://github.com/dj-yacine-flutter/brain_fusion

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  test: ^1.24.2

